# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
#
templates:
  params:
    author-email: eternal.kadir@gmail.com
    author-name: Lukasz Czaplinski
    category: languages
    copyright: MIT
    github-username: scoiatael
