image: alpine/edge
sources:
  - https://git.sr.ht/~scoiatael/dotfiles
secrets:
  - 40802342-277b-4d48-acef-164e1fd2603b
tasks:
  - mirror: |
      cd dotfiles
      echo -e "Host github.com\n  IdentityFile /home/build/.ssh/40802342-277b-4d48-acef-164e1fd2603b\n  IdentitiesOnly yes\n  BatchMode yes" >> ~/.ssh/config
      cat <<EOF > ~/.ssh/known_hosts
        # github.com:22 SSH-2.0-babeld-4b034cc8
        github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        # github.com:22 SSH-2.0-babeld-4b034cc8
        # github.com:22 SSH-2.0-babeld-4b034cc8
        # github.com:22 SSH-2.0-babeld-4b034cc8
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
        # github.com:22 SSH-2.0-babeld-4b034cc8
        github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      EOF
      git remote add github git@github.com:scoiatael/dotfiles
      git push --prune github +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
